---
title       : Weekly Expense Manager
subtitle    : Developing Data Products Project
author      : Catherine Li
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Motivation and Objectives

1. Market: There are a lot of apps in the market that help with expense management. Many of them ask users to enter their MONTHLY budget and each transaction amount. In return, they tell users their balances.

2. Problems of these apps: The time horization is too long. People may lose focus and motivation.

3. Objectives of this app: This small app uses 7-day time horizon, which provides a much quicker monitor of a user's financial situation.

--- .class #id 

## How does the app work: Input and Output

1. Overview: This app is very intuitive. It asks a user for inputs including the week, the budget for the week and total expenses that occured on each day during the week. After a user clicks submit button, it generates three outputs: total spending, remaining balance, and a pie chart. 


2. Input: (1) date: user needs to specify which week (2) weekly budget: default is 500 dollars (3) expense on each day from Monday through Sunday: default is 0 dollars. 

3. Output: (1) total spending (2) total remaining balance (3) a pie chart 

---. class #id

## Here is an example
Say for the week of April 13th 2015, your weekly budget is 500 dollars. You spent 100 dollars on Monday and 50 dollars on Tuesday. You have not spent anything for the rest of the week.  

```{r, echo=TRUE, fig.height=5}
budget<-500;Mon<-100;Tue<-50;Wed<-0;Thu<-0;Fri<-0;Sat<-0;Sun<-0;
total<-sum(Mon, Tue, Wed, Thu, Fri, Sat, Sun);balance<-budget-total;
pie(c(total, balance), labels=c("spending", "remaining"),col=rainbow(2))
```

---. class #id

## Example Condinued
After you clicked submit, three outputs are generated by this app. The total spending is `r total`, the remaining balance is `r balance`, and the pie chart is also plotted.